# -*- coding: utf-8 -*-
"""NYU_DATA_SCIENCE_BOOTCAMP_WEEK2_Take_Home_Exercises.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19e4Z9GOUsKcplpgr54a8klz1CHj4fyof
"""

import numpy as np

A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[7, 8, 9], [10, 11, 12]])

vertically_stacked = np.vstack((A, B))
print("Vertically Stacked:\n", vertically_stacked)

horizontally_stacked = np.hstack((A, B))
print("Horizontally Stacked:\n", horizontally_stacked)

A_flat = A.flatten()
B_flat = B.flatten()

common_elements = np.intersect1d(A_flat, B_flat)
print("Common Elements:\n", common_elements)

min_value = 5
max_value = 10

elements_in_range = A[(A >= min_value) & (A <= max_value)]
print("Elements in range 5 to 10:\n", elements_in_range)

import numpy as np

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

filtered_iris = iris_2d[(iris_2d[:, 2] > 1.5) & (iris_2d[:, 0] < 5.0)]

print(filtered_iris)

import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

filtered_df = df.loc[::20, ['Manufacturer', 'Model', 'Type']]

print(filtered_df)

import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

df['Min.Price'].fillna(df['Min.Price'].mean(), inplace=True)

df['Max.Price'].fillna(df['Max.Price'].mean(), inplace=True)

print(df[['Min.Price', 'Max.Price']].head())

import pandas as pd
import numpy as np

df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))

filtered_rows = df[df.sum(axis=1) > 100]

print(filtered_rows)